config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, only: [:new, :create, :show, :destroy, :edit, :update]
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :sub_id, :author_id, presence: true

  belongs_to :sub
  belongs_to :author, class_name: 'User'
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :moderator_id, presence: true

  belongs_to :moderator, class_name: 'User'
  has_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :session_token, uniqueness: true

  after_initialize :ensure_session_token

  attr_reader :password

  has_many :posts, foreign_key: :author_id

  has_many :subs, foreign_key: :moderator_id

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    return nil unless user
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :require_user_login, :require_moderator


  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def require_user_login
    if current_user.nil?
      redirect_to new_session_url
    end
  end

  def require_moderator
    @sub = Sub.find(params[:id])
    unless current_user && (current_user == @sub.moderator)
      redirect_to sub_url(@sub)
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render :login
  end

  def create
    @user = User.find_by_credentials(user_params[:username], user_params[:password])
    if @user.nil?
      render :login
    else
      @user.reset_session_token!
      session[:session_token] = @user.session_token
      redirect_to user_url(@user)
    end
  end

  def destroy
    session[:session_token] = nil
    redirect_to new_session_url
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :require_moderator, except: [:show, :index]

  def new
    render :new
  end

  def create
    @sub = current_user.subs.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      redirect_to new_sub_url
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def edit
    @sub = Sub.find(params[:id])
    @action = :patch
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      redirect_to edit_sub_url(@sub)
    end
  end

  def index
    @subs = Sub.all
    render json: @subs
  end



  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_user_login, except: [:new, :create]
  #skip_before_action :require_user_login, only: [:new, :create]

  def new
    # @user = User.new
    render :signup
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def show
    @user = User.find(params[:id])
    if @user == current_user
      render :show
    else
      fail
      redirect_to subs_url
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def force_action(action)
    <<-HTML.html_safe
     <input type="hidden" name="_method" value="#{h(action.to_s)}">
    HTML
  end

  def our_button_to(value, action_url, method)
    <<-HTML.html_safe
    <form action="#{h(action_url)}" method="#{h(method.to_s)}">
      <input type="submit" value="#{h(value)}">
    </form>
    HTML
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_form.html.erb
<% url = @user.nil? ? users_url : session_url %>
<%# byebug %>

<form action="<%= url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="user_username">Username</label>
    <input type="text" name="user[username]" value="" id = "user_username">

  <label for="user_password">Password</label>
    <input type="password" name="user[password]" value="" id = "user_password">
  <input type="submit">
</form>

app/views/subs/_form.html.erb
<% url = method.nil? ? subs_url : sub_url(subreddit) %>

<form action="<%= url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <%= force_action(method) unless method.nil? %>
  <label for="sub_title">Title</label>
    <input type="text" name="sub[title]" value="" id = "sub_title">
  <br>
  <br>
  <label for="sub_description">Description</label>
  <br>
    <input type="textarea" name="sub[description]" value="" id = "sub_description">
  <input type="submit">
</form>

app/views/subs/edit.html.erb
<h1>Edit Subreddit</h1>

<%= render "form", method: @action, subreddit: @sub %>

app/views/subs/new.html.erb
<h1>Create a Sub</h1>
<%= render "form", method: nil %>

app/views/subs/show.html.erb
<h1>Subreddit: <%= @sub.title %> </h1>
<br>
<br>

<%= our_button_to("Edit", edit_sub_url, :get) %>

app/views/users/show.html.erb
<h1>Hello <%= @user.username %></h1>

<form action="<%= session_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Logout">
</form>

app/views/users/signup.html.erb
<h1>Create Account</h1>
<%= render "shared/form" %>